### ISSUE TITLE
[design] figma 수정된 디자인 반영

### ISSUE THREAD

**Issue by jordan-choi** [ReactMasters/todolist#28]
## Feature description

- 완료된 todoItem 펼침/닫힘 기능 

## Figma

https://www.figma.com/file/Owjb8d0ZqRKgoab2uSwZt7/Todolist-%2B-MUI?node-id=4213%3A1335

**Comment by JeGwan** [comment]
@hyeonjoo 님 의견
- 삭제 기능
- 간단하게 태스크 추가하면 좋겠다
- due date 오늘, 내일, 다음주는 간단한 버튼으로 있음 좋겠다.
- todo 적는게 가볍고 심플해야한다.
- 책 읽기? 한국 영어? 하위 태그를 선택하고 싶다?

**Comment by yuico** [comment]
@hyeonjoo @56aiden90 님 의견 참고
고도화
- 메뉴: 중요 체크 표시한 todo만 보는 기능
- 메뉴: 만들어 둔 todo 가져오는 기능

**Comment by hyeonjoo** [comment]
Figma Pages의 TodoList Design HJ, Components HJ 에서 작업.

작업 체크 리스트
- [x] 전체 그룹(tag) sum 해서 보여주기
- [x] Important 표시될 항목은 태그 활용
- [x] Completed 표시는 collapse로 (MS Todo 참고)
- [x] Todo 추가 디자인. MS TODO 참고- 추가하는 UI가 가장 심플. 짧은 한줄로 Add a Task, 아래에 버튼 3개: 태그 설정, Due Date
- [ ] Todo 수정, 삭제 디자인. 세부 수정은 항목을 누르면 들어가고, 꾹 눌러서 multiple 수정/삭제
- [x] 기한 표시 디자인. 1) 기한이 있을 때 한줄 작게 날짜 추가, 2) 기한이 넘었고 미완료일 때, 가볍게 날짜를 빨갛게 표시
- [x] 기한 설정 디자인. 총 4가지- 오늘, 내일, 다음주(요일은 추천됨), 날짜정하기 로 (MS Todo 참고)
- [x] 멀티태그
- [ ] 필터링과 정렬- 태그, 날짜(기한;필요있는지는 의문), 소유

논의할 거리
- 태그가 다 선택되어있는데 다시 하나만 선택하고 싶을 때의 UX
- 태그가 없는 것만 볼수있는 태그도 만들어야 할까?
- 캘린더뷰는 고도화에서 하는것인지?

**Comment by hyeonjoo** [comment]
고도화 리스트
1. 오늘 또는 캘린더의 각 날짜에
- 기한이 없는 할일을 선택하여 추가할 수 있는 기능 (MS Todo 참고)
- 기한이 있지만 미완료인 일을 선택하여 추가할 수 있는 기능 (MS Todo 참고)
2. 그룹에 대한 고도화
- 태그 대신에 노션 페이지처럼 되는 그룹 개념 도입
3. 리마인더 기능
- 시간을 감지해서 오늘 점심/ 오늘 이따가/ 내일 / 다음주 / 시간날짜 pick 이렇게 해놓은거 보고 감탄함 (MS Todo 참고)
4. 태그 구조화
- 필터링하고 정돈할때 편할 것. 예를 들면 책이라는 태그에 한국어책, 영어책 이렇게 하위 태그로 들어가고, 나중에 필터링해서 할일을 볼 때는 책을 선택하면 둘 다 나오게끔


참고한 후 추천하는 Todo 어플
1. UX
- MS Todo(In General) - 안드로이드, 아이폰, 웹, 맥, 윈도우 다 있음
- Daily Tasks: To Do & Routines(캘린더 핸들링) - 안드로이드만 있음
2. 디자인
- MS Todo: 심플, 직장인
- To Do List - Tasks & Reminders from Monelyze Inc): 심플, 퍼스널
3. 태그 핸들링에 참고하면 좋을 것
- Do!: 태그바
- Daily Tasks: To Do & Routines
